name: CD with Docker
on:
  push:
    branches: [ "main", "develop" ]

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Environment
        run: echo "${{ secrets.ENV_PROPERTIES }}" > ./.env

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test and Build
        run: |
          ./gradlew clean test -Pprofile=test
          ./gradlew clean build

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }} .

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Send env file
        uses: appleboy/scp-action@master
        with:
          username: ubuntu
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./.env"
          target: "/home/ubuntu"

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker stop ${{ secrets.DOCKER_REPOSITORY }}
            sudo docker rm ${{ secrets.DOCKER_REPOSITORY }}
            sudo docker image prune -a -f
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
            sudo docker run -d --log-driver=syslog --env-file .env -p 8080:8080 --name ${{ secrets.DOCKER_REPOSITORY }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
